const fs = require('fs');
const path = require('path');

function assert(condition, message){
  if(!condition) throw new Error(message);
}

const source = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'post.js'), 'utf8');
const cinematicFlareSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'cinematic-lens-flare.js'), 'utf8');
const skySource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'sky.js'), 'utf8');
const cameraSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'player-camera.js'), 'utf8');
const editorCoreSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'editor', 'editor-core.js'), 'utf8');
const editorRuntimeSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'editor', 'editor-runtime.js'), 'utf8');
const volumetricCloudSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'volumetric-clouds.js'), 'utf8');
const playerLightRigSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'player-light-rig.js'), 'utf8');
const lotKingSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'lot-king.js'), 'utf8');
const renderingBackendSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'rendering-backend.js'), 'utf8');
const consolePolicySource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'console-policy.js'), 'utf8');
const modelAssetsSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'model-assets.js'), 'utf8');
const sceneStoreSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'engine', 'scene-store.js'), 'utf8');
const materialEditorSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'editor', 'material-editor.js'), 'utf8');
const radioHudSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'radio-hud.js'), 'utf8');
const driveTuningSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'drive-tuning.js'), 'utf8');
const engineControllerSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'vehicle-engine-controller.js'), 'utf8');
const vehiclePawnSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'vehicle-pawns.js'), 'utf8');
const physicsWorldSource = fs.readFileSync(path.join(__dirname, '..', 'js', 'runtime', 'physics-world.js'), 'utf8');

assert(source.includes('float emitter = smoothstep(1.10, 2.40, bright)'), 'volumetric shafts are sourced only by HDR emitters');
assert(source.includes('emitter *= sourceMask'), 'volumetric shafts reject aligned headlights and bright SSR pixels outside the sun source');
assert(source.includes('opticalState.ndcX') && source.includes('opticalState.ndcY'), 'volumetric lighting follows the same camera-relative sun projection as the optical flare');
assert(!source.includes('smokeDensity = smoothstep'), 'bright neutral scene meshes are not misclassified as smoke');
assert(source.includes('onScreen = !!opticalState.visible') && source.includes('onScreen = inFront &&'), 'volumetric lighting is disabled when its optical or fallback source is behind or outside the camera');
assert(source.includes('new THREE.SSRPass'), 'ray reflections use the official Three.js SSR pass when available');
assert(source.includes('new THREE.GTAOPass'), 'stable WebGL rendering uses the official r185 GTAO pass');
assert(source.includes("gtaoProfileKey!==profileKey"), 'GTAO quality changes rebuild shaders only when the profile changes');
assert(source.includes('video&&video.ambientOcclusion!==false'), 'GTAO follows the shared project/player setting');
assert(source.includes('ssrPass.isSelective = true'), 'SSR is restricted to reflective metallic meshes');
assert(source.includes('ssrPass.resolutionScale = profile.resolutionScale'), 'SSR quality controls its internal resolution');
assert(source.includes('video && video.reflectionDistance'), 'SSR ray reach follows the project/player setting');
assert(source.includes('mat.metalness >= .35'), 'SSR excludes ordinary rough ground materials');
assert(source.includes('uniforms.cameraProjectionMatrix.value.copy(activeCamera.projectionMatrix)'), 'SSR depth reconstruction follows the active camera projection every frame');
assert(source.includes('/max(a,0.00001)'), 'SSR blur keeps no-hit sky pixels finite and transparent');
assert(source.includes('target === this.ssrRenderTarget || target === this.blurRenderTarget || target === this.blurRenderTarget2'), 'SSR reflection intermediates are cleared between frames');
assert(source.includes('node.userData.lkSkipSsrOverride === true'), 'GPU-deformed transparent effects are excluded from incompatible SSR override passes');
assert(source.includes('node.userData.lkSkipSsrBeauty === true') && source.includes('state.readBuffer.texture'), 'optical billboard lights are excluded from SSR ray sources without disappearing from the normal beauty image');
assert(!source.includes('vec3 reflected=max(base-bounce'), 'indirect ray lighting does not add a high-pass halo over the whole frame');
assert(source.includes('low:{contrast:1, saturation:1, brightness:0'), 'quality presets keep color and illumination neutral');
assert(source.includes('videoOnly'), 'editor cameras can render the shared video pipeline without player-camera grading');
assert(source.includes('renderPass.camera = activeCamera'), 'the shared post pipeline accepts editor and gameplay cameras');
assert(source.includes('function needsPost()') && source.includes("video&&video.visualStyle==='illustrated-sketch'"), 'WebGPU enters its TSL post graph only for effects that graph implements');
assert(source.includes("submission&&typeof submission.then==='function'") && source.includes('submission.catch(failToDirect)'), 'an asynchronous WebGPU pipeline failure retires post and restores direct scene rendering');
const webgpuEligibility=source.slice(source.indexOf('function needsPost()'),source.indexOf('function render(cameraOverride,options)'));
assert(!webgpuEligibility.includes('volumetricLighting'), 'legacy volumetric selection cannot replace a valid Natural WebGPU frame with an empty target');
assert(editorRuntimeSource.includes('post.webgpu && post.needsPost'), 'the Editor asks the active WebGPU post graph whether it is required');
assert(lotKingSource.includes('POST&&POST.webgpu&&POST.needsPost'), 'Play and standalone game use the same WebGPU post eligibility contract');
assert(lotKingSource.includes('GAME.systems.post.dispose') && lotKingSource.includes('GAME.systems.pathTracing.dispose'), 'iframe renderer handoff releases post and path-tracing GPU allocations explicitly');
assert(renderingBackendSource.includes("device.addEventListener('uncapturederror'") && renderingBackendSource.includes('GPU_QUARANTINE_KEY'), 'native WebGPU validation storms are grouped and session-quarantined before exhausting the GPU process');
assert(consolePolicySource.includes("lotking:webgpu-console-error") && consolePolicySource.includes('gpuConsoleSignature'), 'Three.js WebGPU console failures are deduplicated and forwarded to structured diagnostics');
assert(source.includes('node.isSprite||data.lkSkipAoGBuffer===true||data.lkFlareIgnore===true||noDepthMaterial'), 'GTAO excludes camera-facing flare sprites and non-depth optical effects from its geometry buffers');
assert(source.includes('new THREE.ShaderPass(THREE.FXAAShader)'), 'FXAA uses the Three.js post-process shader');
assert(source.includes('new THREE.OutputPass()'), 'modern Three.js output color conversion is explicit in the composer');
assert(source.includes('LK_RUNTIME_CINEMATIC_LENS_FLARE.createPass'), 'the selectable cinematic sun flare is part of the shared post pipeline');
assert(source.includes('lensFlareState(activeCamera)'), 'cinematic flare projection follows the active editor or gameplay camera');
assert(cinematicFlareSource.includes('lensDirtTexture'), 'cinematic flare retains the licensed lens-dirt optical modulation');
assert(cinematicFlareSource.includes('for (int i = 0; i < 8; i++)'), 'cinematic flare renders a bounded configurable optical ghost chain');
assert(cinematicFlareSource.includes('float dotDistance = length(p-mouse*dist/.5)') && cinematicFlareSource.includes('exp(-(dotDistance*dotDistance)'), 'cinematic point ghosts use bounded soft cores instead of flickering reciprocal singularities');
assert(cinematicFlareSource.includes('bloomRadius') && cinematicFlareSource.includes('bloomThreshold'), 'cinematic sun bloom exposes authored radius and threshold');
assert(cinematicFlareSource.includes('new THREE.WebGLRenderTarget') && cinematicFlareSource.includes('resolutionScale'), 'cinematic optics render into an independently scaled HDR target');
assert(cinematicFlareSource.includes('base.rgb+texture2D(tOptics,vUv).rgb'), 'reduced-resolution optics are composited over the untouched full-resolution scene');
assert(source.includes('resolutionScale:.5') && source.includes('resolutionScale:.42'), 'sun and local-light cinematic optics use bounded half-resolution profiles');
assert(source.includes('function needsOpticalPost(nextCamera)') && source.includes('cinematicOpticsEnabled()?collectSceneFlareStates(activeCamera):[]'), 'cinematic sun and authored-light optics remain available independently from volumetric shafts');
assert(source.includes('cinematicFlarePass.updateFromState(state,currentSize.width,currentSize.height)'), 'disabling volumetric lighting does not disable the cinematic sun flare or bloom');
assert(source.includes('function cinematicOpticsEnabled()') && source.includes('if(!cinematicOpticsEnabled()) return false'), 'the separate cinematic lens-flare setting bypasses every advanced optical pass');
assert(playerLightRigSource.includes('flareIntensity:.24') && playerLightRigSource.includes('flareIntensity:.16'), 'front and rear vehicle flare pairs have independent restrained defaults');
assert(playerLightRigSource.includes('glow:false, bloom:true') && playerLightRigSource.match(/glow:false, bloom:true/g).length >= 2, 'front and rear vehicle glow sprites are disabled by default');
assert(playerLightRigSource.includes('updateLampMaterialEmission(frontActive||previewEmission,braking,reversing)'), 'vehicle state and editor preview update the authored lamp mesh materials');
assert(playerLightRigSource.includes('material.emissive.copy(color)') && playerLightRigSource.includes('highBeamEmissiveIntensity') && playerLightRigSource.includes('braking?4.1:1.35'), 'front, high-beam, rear and brake states receive distinct configurable emissive strength');
assert(playerLightRigSource.includes('flareBloomIntensity:.19') && playerLightRigSource.includes('flareBloomIntensity:.12'), 'vehicle flare bloom is authored and persisted independently for front and rear pairs');
assert(playerLightRigSource.includes('f.flareOcclusion') && playerLightRigSource.includes('r.flareOcclusion'), 'front and rear vehicle flare occlusion reaches the runtime optical sources');
assert(playerLightRigSource.includes('f.flareIntensity == null ? .24 : f.flareIntensity'), 'both front headlights use the same authored pair flare power without high-beam amplification');
assert(playerLightRigSource.includes('!!r.flare && cinematicPair === true') && playerLightRigSource.includes('rig.rear.position'), 'only the rear position-light pair emits cinematic flare instead of stacking brake and reverse sources');
assert(playerLightRigSource.includes('item.glow.scale.setScalar(f.glowSize)') && playerLightRigSource.includes('item.flare.scale.setScalar(f.flareSize)'), 'high beams preserve the authored front-light dummy and sprite footprint');
assert(!playerLightRigSource.includes('f.glowSize * (1 + highBeamBoost') && !playerLightRigSource.includes('f.flareSize * (1 + highBeamBoost'), 'high beams never make vehicle light markers appear to move by resizing their selected bounds');
assert(playerLightRigSource.includes('function pinEmitterToAnchor(item)') && playerLightRigSource.includes('[item.light, item.point, item.glow, item.flare]'), 'every vehicle emitter and optical sprite is pinned to the exact dummy origin');
assert(playerLightRigSource.includes('s.userData.lkSkipSsrBeauty = true'), 'vehicle glow and flare sprites cannot become fake luminous SSR geometry');
assert(playerLightRigSource.includes('function syncAnchorTransforms(resolveSource)') && playerLightRigSource.includes('anchorMatrix.decompose(anchor.position, anchor.quaternion, anchor.scale)'), 'Vehicle Pawn runtime lights inherit the authored Logic Element dummy transform');
assert(skySource.includes('node.userData.editorCameraHelper') && skySource.includes('node.userData.lkFlareIgnore'), 'editor camera helpers never occlude the sun flare');
assert(!skySource.includes("node.userData.editorType === 'player' || node.userData.vehiclePawnId"), 'real Player Car geometry keeps normal sun depth occlusion');
assert(skySource.includes('sunPositionForCamera(camera,_fs,250)') && skySource.includes('sunSprite.onBeforeRender'), 'sun visuals and optical projection are camera-relative sky directions');
assert(skySource.includes('celestialDistance(camera,330)') && skySource.includes('far * .78'), 'celestial visuals stay inside each active camera far plane');
assert(skySource.includes('flareHitTransmission') && skySource.includes('material.transmission') && skySource.includes('flareTextureAlpha'), 'clouds, smoke and glass attenuate optical visibility according to alpha/transmission');
assert(skySource.includes('Math.pow(sourceTransmission,.55)') && skySource.includes('sourceTransmission,'), 'cinematic flare uses a dedicated photographic transmission response');
assert(!skySource.includes("document.body.classList.contains('lk-volumetric-lighting')") && skySource.includes("document.body.classList.contains('lk-cinematic-lens-flares')"), 'cinematic flare selection has its own video control independent from volumetric lighting');
assert(volumetricCloudSource.includes('dome.userData.lkFlareTransmission') && volumetricCloudSource.includes('flareDensity'), 'volumetric-cloud flare transmission samples the moving authored density field');
assert(editorCoreSource.includes('helperGroup.userData.lkFlareIgnore = true'), 'the complete editor helper group is excluded from optical occlusion');
assert(editorRuntimeSource.includes('Number(GAME.player.cameraCfg.helperRange) || 5'), 'the editor camera cone uses a compact authored range instead of the gameplay far plane');
assert(cameraSource.includes('freePitch: .32') && cameraSource.includes('helperSize: .7'), 'camera placement and helper sizing have persistent defaults');
assert(cameraSource.includes('interiorLateral: -.42') && lotKingSource.includes("mode === 'interior'"), 'native and Logic vehicles share a left-hand-drive steering-aligned interior camera');
assert(cameraSource.includes('interiorNear: .1') && cameraSource.includes('interiorFocusDistance: 9') && lotKingSource.includes("mode==='interior' ? CAM_CFG.interiorNear : CAM_CFG.near"), 'external and interior vehicle camera optics are authored independently and consumed by Play');
assert(cameraSource.includes('interiorGForceMotion: 0') && cameraSource.includes('interiorAccelerationMotion: 0') && cameraSource.includes('interiorRoadShake: 0'), 'all cockpit translation and vibration are disabled by default');
assert(lotKingSource.includes('interiorTargetOffset.clampLength(0, motionLimit)'), 'optional cockpit motion is constrained to the authored cabin safety range');
assert(lotKingSource.includes('camPos.copy(want)') && lotKingSource.includes("if(mode === 'interior') camLook.copy(look)"), 'interior camera position and aim remain rigidly attached instead of lagging in world space');
assert(lotKingSource.includes("const sh = mode === 'interior' ? 0"), 'generic impact shake cannot move the cockpit camera outside its cabin mount');
assert(lotKingSource.includes('interiorSpeedFovGain') && lotKingSource.includes('interiorSpeedFovMax'), 'interior speed FOV has independent gain and a restrained authored maximum');
assert(lotKingSource.includes('Math.sin(interiorShakePhase') && !lotKingSource.includes('Math.random() * interiorRoadShake'), 'cockpit road vibration is deterministic instead of frame-random jitter');
assert(lotKingSource.includes("'player_camera_external'") && lotKingSource.includes("'player_camera_interior'"), 'the native vehicle exposes persistent external and interior camera dummies');
assert(lotKingSource.includes('syncPlayerCameraConfigFromDummy') && editorRuntimeSource.includes('GAME.player.cameraDummies'), 'camera dummy gizmos drive the authored camera config and remain editor-only');
assert(lotKingSource.includes('interiorDummy.getWorldPosition(want)') && lotKingSource.includes('interiorDummy.getWorldQuaternion(interiorCameraWorldQuaternion)'), 'the runtime cockpit camera copies one complete world transform from its authored dummy');
assert(lotKingSource.includes('lookBack ? -12 : 12') && (lotKingSource.match(/if\(lookBack\) camera\.rotateY\(Math\.PI\)/g)||[]).length >= 2, 'mapped Look Back survives both cockpit and authored external-camera rotation while preserving camera position');
assert(editorRuntimeSource.includes('interiorDummy.getWorldPosition(gameCam.position)') && editorRuntimeSource.includes('interiorDummy.getWorldQuaternion(gameCam.quaternion)'), 'the editor cockpit preview uses the exact same dummy transform as gameplay');
assert(editorRuntimeSource.includes('syncPlayerDummyPreviewCamera(selectedPlayerCamera)') && editorRuntimeSource.includes("data.editorType === 'playerCamera'"), 'selecting a player camera renders that exact dummy in the floating preview independently of the active gameplay mode');
assert(skySource.includes('nightEnvironment:1') && skySource.includes('LIGHTING.moonIndirect=clampf(Number(LIGHTING.moonIndirect)||0,0,4)') && skySource.includes('LIGHTING.nightEnvironment=clampf(Number(LIGHTING.nightEnvironment)||0,0,5)'), 'night indirect and environment response have useful extended authoring ranges');
assert(modelAssetsSource.includes("pick('steering_wheel_pivot')") && modelAssetsSource.includes('lkSteeringRig') && modelAssetsSource.includes('steeringReady'), 'vehicle model rigs expose the future Blender steering-wheel pivot convention');
assert(materialEditorSource.includes("value:'vehicle-hud'") && materialEditorSource.includes("value:'radio-hud'") && materialEditorSource.includes("value:'youtube'") && materialEditorSource.includes("value:'video'"), 'specific material slots expose telemetry, Radio TAB, official YouTube and direct-video surface modes');
assert(sceneStoreSource.includes('dynamicMaterialTextures') && sceneStoreSource.includes('drawDynamicVehicleHud') && sceneStoreSource.includes('drawDynamicRadioHud') && sceneStoreSource.includes('dynamicRefreshHz'), 'dynamic dashboard textures use a shared throttled runtime update path');
assert(sceneStoreSource.includes('www.youtube-nocookie.com') && sceneStoreSource.includes('parseYouTubeSurfaceUrl'), 'YouTube links use the official privacy-enhanced iframe surface instead of scraping page pixels');
assert(materialEditorSource.includes('Override Base Color with this screen') && materialEditorSource.includes('dynamicMapEnabled'), 'dynamic material screens expose a persistent non-destructive Base Color override toggle');
assert(sceneStoreSource.includes('function applyDynamicMaterialOverride') && sceneStoreSource.includes('material.color.set(0xffffff)') && sceneStoreSource.includes('material.vertexColors = false'), 'dynamic screens neutralize imported GLB tint and vertex colors instead of rendering black');
assert(sceneStoreSource.includes('function restoreDynamicMaterialBase') && sceneStoreSource.includes('material.color.copy(base.color)'), 'disabling a dynamic screen restores the protected GLB color and texture');
assert(sceneStoreSource.includes('function ensureDynamicScreenUv') && sceneStoreSource.includes("attributeName:'uv3', channel:3") && materialEditorSource.includes('Auto-fit screen UV'), 'dynamic screens auto-fit through a spare UV channel without overwriting imported GLB UVs');
assert(sceneStoreSource.includes('function applyDynamicTextureTransform') && sceneStoreSource.includes('dynamicRepeatX') && materialEditorSource.includes('Fit screen UV 1:1'), 'screen repeat, offset and rotation are independent from the protected base material and expose a one-click neutral fit');
assert(sceneStoreSource.includes('if(!m.lkDynamicTextureController) applyTextureTransform(m.map, patch)'), 'legacy base-map transforms cannot overwrite the active dynamic screen transform');
assert(materialEditorSource.includes('const dynamicDraft = {') && materialEditorSource.includes('Object.assign(dynamicDraft, extra || {})'), 'screen UV and appearance sliders accumulate live values instead of resetting sibling controls from a stale Inspector snapshot');
assert(materialEditorSource.includes('Screen roughness') && materialEditorSource.includes('Screen metalness') && materialEditorSource.includes('Screen saturation'), 'dynamic screens expose independent reflection and color controls');
assert(sceneStoreSource.includes('function installDynamicSaturationShader') && sceneStoreSource.includes('lkDynamicScreenSaturation'), 'screen saturation runs as a GPU uniform instead of CPU texture readback');
assert(sceneStoreSource.includes('material.roughnessMap = null') && sceneStoreSource.includes('material.metalnessMap = null'), 'screen PBR sliders are not silently multiplied by imported roughness or metalness maps');
assert(sceneStoreSource.includes('hitUvForTexture') && sceneStoreSource.includes("channel === 3 ? 'uv3'") && sceneStoreSource.includes('THREE.Triangle.getBarycoord'), 'interactive material raycasts use the same spare UV channel displayed by the dynamic screen');
assert(sceneStoreSource.includes('GAME.player.runtimeInteractionRect') && sceneStoreSource.includes('GAME.player.surfaceInteractionEnabled'), 'dynamic surfaces raycast inside the rendered Play Preview frame and only while the interaction cursor is active');
assert(sceneStoreSource.includes("window.addEventListener('pointerdown', pointerDown, true)") && sceneStoreSource.includes('runtimeUiTarget'), 'interactive screens listen above transparent editor chrome without stealing real UI controls');
assert(sceneStoreSource.includes("radio.toggleOpen(true)") && sceneStoreSource.includes("recordInteraction('activated'"), 'Radio material clicks always have a visible fallback and publish a diagnostic result');
assert(lotKingSource.includes("if(key === 'y')") && lotKingSource.includes('toggleRuntimeInteractionCursor'), 'Y is the shared gameplay and Play Preview interaction-cursor toggle');
assert(sceneStoreSource.includes('bindDynamicSurfaceProxy') && sceneStoreSource.includes('lkDynamicSurfaceController'), 'dynamic material controls own an exact material-face interaction proxy independent from imported GLB slot lookup');
assert(driveTuningSource.includes('frontDriveBias:0') && lotKingSource.includes('engineForces:[frontWheelForce,frontWheelForce,rearWheelForce,rearWheelForce]'), 'native Drift defaults to RWD and distributes drive force explicitly per axle');
assert(vehiclePawnSource.includes('frontDriveBias') && vehiclePawnSource.includes('engineForces[index] = engineForce * (1 - frontDriveBias)'), 'Logic Vehicle Pawns share the authored axle drive distribution instead of implicitly powering every wheel');
assert(engineControllerSource.includes('boostTarget') && engineControllerSource.includes('state.boost01') && engineControllerSource.includes('Math.exp(-boostRate'), 'turbo torque uses persistent progressive spool pressure rather than an RPM threshold step');
assert(driveTuningSource.includes('frontSuspension') && driveTuningSource.includes('rearDamping') && physicsWorldSource.includes("axleValue(front, 'stiffness')"), 'front and rear suspension stiffness/damping controls reach the native raycast wheels');
assert(sceneStoreSource.includes('retainDynamicRadioSurface(controller)') && radioHudSource.includes('runtimeAvailability({') && radioHudSource.includes('if(!available && !editorPreview) return false;'), 'an authored Radio HUD material mirrors the vehicle radio but cannot create ambient level playback');
assert(radioHudSource.includes('playFromSurface') && radioHudSource.includes('RADIO PLAYBACK FAILED'), 'material radio controls initialize audio from the user gesture and report playback failures');
assert(lotKingSource.includes('cockpitInteractionSlowMotionRequested') && lotKingSource.includes('requested && !runtimeSinglePlayer()') && lotKingSource.includes('state.peerCount > 0'), 'cockpit cursor slow-motion is guarded against local and P2P multiplayer');
assert(sceneStoreSource.includes('uses.get(material)') && sceneStoreSource.includes('lkMaterialSlotInstance'), 'per-mesh dynamic surfaces split shared glTF material references before editing');
assert(!lotKingSource.includes('camMode'), 'Free Camera must not depend on a second legacy chase/orbit sub-state');
assert(lotKingSource.includes('return pointInRuntimeViewport(e)') && lotKingSource.includes('runtimeCameraAllowsMouseLook(e)'), 'Play Preview mouse look recognizes the viewport before pointer lock');
assert(!lotKingSource.includes('userCamTimer'), 'Free Camera cannot silently time out and return to chase behavior');
assert(lotKingSource.includes('anchor.add(p.flame)') && lotKingSource.includes('p.flame.position.set(0,0,0)'), 'exhaust fire remains welded to the authored outlet instead of becoming a smoke particle');
assert(lotKingSource.includes('GAME.hooks.warmup.push(context=>') && lotKingSource.includes('spawnExhaustParticle(anchor,true'), 'the pre-benchmark renders the real exhaust flame shader before gameplay');
assert(lotKingSource.includes('exhaustFireEdges.hot=hotFire') && lotKingSource.includes('exhaustFireBurst=Math.max'), 'native exhaust fire is edge-triggered as a finite burst');
assert(lotKingSource.includes('exhaustFireNext=.075+Math.random()*.085') && lotKingSource.includes('(.038 + Math.random() * .026)'), 'tuning backfire uses separated irregular flashes instead of an overlapping fixed flame');
assert(lotKingSource.includes('if(!p.s.visible&&!p.flame.visible) continue'), 'exhaust lifecycle advances both smoke sprites and the separate anchored flame meshes');
assert(source.indexOf('new THREE.OutputPass()') < source.indexOf('new THREE.ShaderPass(THREE.FXAAShader)'), 'OutputPass runs before display-space FXAA');
assert(source.includes("video.antialiasing === 'fxaa'"), 'FXAA pass follows the shared video setting');

console.log('post-processing.test.js: all assertions passed');
