'use strict';
const assert=require('node:assert/strict');global.window=global;
class Vec3{constructor(x=0,y=0,z=0){this.set(x,y,z);}set(x,y,z){this.x=x;this.y=y;this.z=z;return this;}}
class Quaternion{setFromEuler(){return this;}setFromAxisAngle(){return this;}}
class Shape{}class Plane extends Shape{}class Box extends Shape{constructor(size){super();this.size=size;}}class Heightfield extends Shape{constructor(data,options){super();this.data=data;this.elementSize=options.elementSize;}}
class Material{constructor(name){this.name=name;}}class ContactMaterial{constructor(a,b,options){Object.assign(this,{a,b},options);}}
class Body{constructor(options){this.mass=options.mass;this.material=options.material;this.shapes=[];this.position=new Vec3();this.quaternion=new Quaternion();this.velocity=new Vec3();this.angularVelocity=new Vec3();this.force=new Vec3();this.torque=new Vec3();this.listeners={};}addShape(shape){this.shapes.push(shape);}addEventListener(name,fn){this.listeners[name]=fn;}removeEventListener(name){delete this.listeners[name];}}
class World{constructor(){this.bodies=[];this.gravity=new Vec3();this.solver={};}addBody(body){this.bodies.push(body);}removeBody(body){const index=this.bodies.indexOf(body);if(index>=0)this.bodies.splice(index,1);}addContactMaterial(){}}
class RaycastVehicle{constructor(){this.wheelInfos=[];}addWheel(info){this.wheelInfos.push(Object.assign({},info));}addToWorld(){}removeFromWorld(){}applyEngineForce(){}setBrake(){}setSteeringValue(){}}
class SAPBroadphase{constructor(world){this.world=world;}}
const CANNON={Vec3,Quaternion,Plane,Box,Heightfield,Material,ContactMaterial,Body,World,RaycastVehicle,SAPBroadphase};
require('../js/runtime/physics-world.js');
const matrix=[[0,0,-4],[0,0,-5],[0,-2,-8]],provider={physicsDescriptor:()=>({signature:'terrain-v1',matrix,elementSize:10,originX:-10,originZ:10})},worldState={colliderSignature:()=>'',colliders:{},sampleDriveSurfaceAt:()=>null},player={pos:new Vec3(),vel:new Vec3(),heading:0,yawRate:0};
const physics=global.LK_RUNTIME_PHYSICS_WORLD.create({CANNONRef:CANNON,worldState,playerState:player,playerCollision:{},colliders:{box:[],circle:[]},terrainProvider:()=>provider});
assert.equal(physics.init(),true);assert.equal(physics.state.groundBody,null,'the infinite Y=0 plane must not cover the ocean');assert.ok(physics.state.terrainBody,'procedural terrain owns world collision');assert.ok(physics.state.terrainBody.shapes[0] instanceof Heightfield);assert.deepEqual(physics.state.terrainBody.shapes[0].data,matrix.map(row=>row.map(value=>value+8)),'Cannon receives non-negative local heights');assert.equal(physics.state.terrainBody.position.x,-10);assert.equal(physics.state.terrainBody.position.y,-8,'the body offset restores exact world heights');assert.equal(physics.state.terrainBody.position.z,10);
const first=physics.state.terrainBody;assert.equal(physics.rebuildStatics(),false,'an unchanged terrain signature does not churn Cannon bodies');assert.equal(physics.state.terrainBody,first);physics.rebuildStatics(true);assert.notEqual(physics.state.terrainBody,first,'an authored terrain rebuild atomically replaces its heightfield');physics.dispose();assert.equal(physics.state.world,null);
const REAL=require('cannon'),realPlayer={pos:new REAL.Vec3(999,0,999),vel:new REAL.Vec3(),heading:0,yawRate:0},realPhysics=global.LK_RUNTIME_PHYSICS_WORLD.create({CANNONRef:REAL,worldState,playerState:realPlayer,playerCollision:{},colliders:{box:[],circle:[]},terrainProvider:()=>provider}),originalWarn=console.warn,originalError=console.error;let result,warnings=0,errors=0;try{console.warn=()=>warnings++;console.error=()=>errors++;realPhysics.init();result=new REAL.RaycastResult();realPhysics.state.world.raycastClosest(new REAL.Vec3(0,50,0),new REAL.Vec3(0,-50,0),{},result);}finally{console.warn=originalWarn;console.error=originalError;}assert.equal(warnings+errors,0,'negative world terrain is locally rebased before Cannon, so it emits no convex-pillar diagnostics');assert.equal(result.hasHit,true,'the real Cannon 0.6.2 ray reaches the procedural heightfield');assert.ok(Math.abs(result.hitPointWorld.y-matrix[1][1])<1e-6,'Cannon orientation matches the rendered X/Z field');realPhysics.dispose();
console.log('procedural-world-physics.test.js: all assertions passed');
