/* =========================================================
   LOT KING - Renderer-neutral procedural water
   Single-pass PBR water: no reflection render targets, safe for WebGL/WebGPU.
   ========================================================= */
(function(root,factory){
'use strict';const api=factory();root.LK_RUNTIME_PROCEDURAL_WATER=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
const TIERS=Object.freeze({low:{segments:30,size:180,hz:20,waves:2},medium:{segments:48,size:240,hz:30,waves:3},high:{segments:72,size:320,hz:45,waves:4},ultra:{segments:96,size:420,hz:60,waves:4}});
const DIRECTIONS=Object.freeze([[.94,.34],[-.52,.85],[.18,.98],[-.86,-.51]]);
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function waveSample(x,z,time,config,waveCount){const amplitude=Math.max(0,Number(config.waveAmplitude)||0),length=Math.max(2,Number(config.waveLength)||42),speed=Math.max(0,Number(config.waveSpeed)||0),count=Math.max(1,waveCount||3);let y=0,dx=0,dz=0;for(let i=0;i<count;i++){const direction=DIRECTIONS[i%DIRECTIONS.length],scale=1+i*.61,k=Math.PI*2/(length/scale),a=amplitude*(i===0?.52:.48/scale),phase=k*(x*direction[0]+z*direction[1])+time*speed*(.8+i*.37);const sine=Math.sin(phase),slope=a*k*Math.cos(phase);y+=a*sine;dx+=slope*direction[0];dz+=slope*direction[1];}return {height:y,dx,dz};}
function material(THREE,config,transparent){const Material=THREE.MeshPhysicalMaterial||THREE.MeshStandardMaterial,params={color:0xffffff,vertexColors:true,roughness:.19,metalness:.06,transparent:transparent!==false,opacity:Number(config.opacity)||.88,depthWrite:false,side:THREE.DoubleSide};if(Material===THREE.MeshPhysicalMaterial){params.clearcoat=.42;params.clearcoatRoughness=.2;params.ior=1.333;}const value=new Material(params);value.name='Procedural Water PBR';return value;}
function colorFor(THREE,config,sample,target){const base=new THREE.Color(config.color||'#187b9b'),deep=new THREE.Color(config.deepColor||'#07344f'),foam=new THREE.Color('#d8f3f1'),slope=clamp(Math.hypot(sample.dx,sample.dz)*2.4,0,1),crest=clamp(sample.height/Math.max(.01,Number(config.waveAmplitude)||.7)*.5+.5,0,1),amount=clamp((slope*.62+crest*.38-.56)*Math.max(0,Number(config.foam)||0)*2.2,0,.78);return target.copy(deep).lerp(base,.7).lerp(foam,amount);}
function animatedSurface(THREE,geometry,config,level,waveCount,alreadyHorizontal){if(!alreadyHorizontal)geometry.rotateX(-Math.PI/2);const position=geometry.getAttribute('position'),base=new Float32Array(position.count*2),colors=new Float32Array(position.count*3),color=new THREE.Color();for(let i=0;i<position.count;i++){base[i*2]=position.getX(i);base[i*2+1]=position.getZ(i);const sample={height:0,dx:0,dz:0};colorFor(THREE,config,sample,color);colors[i*3]=color.r;colors[i*3+1]=color.g;colors[i*3+2]=color.b;}geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));const mesh=new THREE.Mesh(geometry,material(THREE,config,true));mesh.position.y=level;mesh.frustumCulled=true;mesh.castShadow=false;mesh.receiveShadow=false;mesh.renderOrder=2;mesh.userData.lkProceduralWater=true;mesh.userData.lkProceduralOwned=true;return {mesh,base,waveCount,level,config};}
function updateSurface(THREE,surface,time,offsetX,offsetZ){const position=surface.mesh.geometry.getAttribute('position'),normal=surface.mesh.geometry.getAttribute('normal'),colors=surface.mesh.geometry.getAttribute('color'),color=new THREE.Color();for(let i=0;i<position.count;i++){const x=surface.base[i*2],z=surface.base[i*2+1],sample=waveSample(x+offsetX,z+offsetZ,time,surface.config,surface.waveCount),length=Math.hypot(sample.dx,1,sample.dz)||1;position.setY(i,sample.height);if(normal)normal.setXYZ(i,-sample.dx/length,1/length,-sample.dz/length);if(colors){colorFor(THREE,surface.config,sample,color);colors.setXYZ(i,color.r,color.g,color.b);}}position.needsUpdate=true;if(normal)normal.needsUpdate=true;if(colors)colors.needsUpdate=true;}
function riverGeometry(THREE,body){const points=body.points||[],half=Math.max(.1,body.width*.5),vertices=[],uv=[],indices=[];for(let i=0;i<points.length;i++){const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)],tx=next[0]-prev[0],tz=next[1]-prev[1],length=Math.hypot(tx,tz)||1,nx=-tz/length,nz=tx/length;vertices.push(points[i][0]+nx*half,0,points[i][1]+nz*half,points[i][0]-nx*half,0,points[i][1]-nz*half);uv.push(0,i/(points.length-1),1,i/(points.length-1));if(i<points.length-1){const a=i*2,b=a+1,c=a+2,d=a+3;indices.push(a,b,c,b,d,c);}}const geometry=new THREE.BufferGeometry();geometry.setIndex(indices);geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geometry.computeVertexNormals();return geometry;}
function build(THREE,config,options){
  options=options||{};const tier=TIERS[options.quality]||TIERS.medium,group=new THREE.Group();group.name='Procedural World · Water';group.userData.lkProceduralOwned=true;const surfaces=[];let far=null;
  if(config.enabled!==false){
    const farGeometry=new THREE.PlaneGeometry(config.extent,config.extent,1,1);farGeometry.rotateX(-Math.PI/2);far=new THREE.Mesh(farGeometry,material(THREE,Object.assign({},config,{opacity:Math.min(.96,(Number(config.opacity)||.88)+.04)}),true));far.name='Procedural Ocean · Horizon';far.position.y=config.seaLevel-.035;far.renderOrder=1;far.castShadow=false;far.receiveShadow=false;far.userData.lkProceduralWater=true;far.userData.lkProceduralOwned=true;group.add(far);
    const near=animatedSurface(THREE,new THREE.PlaneGeometry(tier.size,tier.size,tier.segments,tier.segments),config,config.seaLevel,tier.waves);near.mesh.name='Procedural Ocean · Animated Near Field';near.snap=Math.max(8,tier.size/12);group.add(near.mesh);surfaces.push(near);
  }
  (options.waterBodies||[]).filter(body=>body&&body.enabled!==false).forEach(body=>{
    let geometry;if(body.type==='river')geometry=riverGeometry(THREE,body);else {geometry=new THREE.CircleGeometry(body.radius,Math.max(32,Math.round(tier.segments*.8)));geometry.scale(body.aspect||1,1,1);geometry.rotateZ(body.rotation||0);}
    const localConfig=Object.assign({},config,body,{waveLength:Math.max(3,(body.radius||body.width||12)*.85),waveSpeed:body.flowSpeed==null?config.waveSpeed:body.flowSpeed,foam:Math.min(.35,config.foam)}),surface=animatedSurface(THREE,geometry,localConfig,body.level,Math.min(2,tier.waves),body.type==='river');surface.mesh.name=body.name;surface.mesh.position.y=body.level;if(body.type==='lake')surface.mesh.position.set(body.center[0],body.level,body.center[1]);group.add(surface.mesh);surfaces.push(surface);
  });
  let elapsed=0,time=0;function update(dt,focus){time+=Math.max(0,Number(dt)||0);elapsed+=Math.max(0,Number(dt)||0);if(elapsed<1/tier.hz)return;elapsed=0;surfaces.forEach((surface,index)=>{if(index===0&&config.enabled!==false&&focus){const snap=surface.snap||16,sx=Math.round((Number(focus.x)||0)/snap)*snap,sz=Math.round((Number(focus.z)||0)/snap)*snap;surface.mesh.position.x=sx;surface.mesh.position.z=sz;updateSurface(THREE,surface,time,sx,sz);}else updateSurface(THREE,surface,time,surface.mesh.position.x||0,surface.mesh.position.z||0);});}
  return Object.freeze({group,update,stats:()=>({drawCalls:(far?1:0)+surfaces.length,animatedVertices:surfaces.reduce((sum,item)=>sum+item.base.length/2,0),tier:options.quality}),surfaceAt:(x,z)=>config.enabled!==false?config.seaLevel:null});
}
return Object.freeze({TIERS,waveSample,riverGeometry,build});
});
